AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - "bin/**/*"
    - "lib/authentic_jwt/payload_pb.rb"
    - "vendor/**/*"
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/WordArray:
  Enabled: false
Layout/LineLength:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
Style/TrailingCommaInArguments:
  Enabled: false
Layout/EmptyLinesAroundClassBody:
  Enabled: false
Layout/EmptyLinesAroundModuleBody:
  Enabled: false
Layout/EmptyLinesAroundBlockBody:
  Enabled: false
Layout/CaseIndentation:
  Enabled: false
Style/Documentation:
  Enabled: false
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
Style/RegexpLiteral:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/TrivialAccessors:
  AllowPredicates: true
Style/NumericLiterals:
  Enabled: false
Layout/ExtraSpacing:
  Enabled: false
Layout/DotPosition:
  Enabled: false
Layout/SpaceInsideBlockBraces:
  Enabled: false
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false
