Style/StringLiterals:
  EnforcedStyle: double_quotes
Lint/Void:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Layout/LineLength:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/AndOr:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Lint/UnusedMethodArgument:
  Enabled: false 
Style/PreferredHashMethods:
  Enabled: false 
Style/FormatStringToken:
  Enabled: false
AllCops:
  Exclude:
    - 'bin/{rails,rake}'
  NewCops: enable
  SuggestExtensions: false